export { default as MainSection } from './MainSection';
export { default as Courses } from './Courses';
export { default as Specialties } from './Specialties';
export { default as ContactSection } from './ContactSection';
export { default as RecentPosts } from './RecentPosts';
export { default as NeedASuperHero } from './NeedASuperHero';
export { default as Certification } from './Certification';
export { default as Varieties } from './Varieties';
export { default as Comments } from './Comments';
