name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # The OS the workflow will run on
    runs-on: ubuntu-latest
    # The versions of node wich will be used
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2

      # Setups the node specific version
      - name: Using Node.js ${{ matrix.node-version }} 🤖
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install the packages
      - name: Instaling packages 📦
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: yarn workspace @iron-linux/frontend run clean-install

      # Builds the app
      - name: Building app ⛏
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: yarn workspace @iron-linux/frontend run build
        env:
          NEXT_PUBLIC_BASE_PATH: "/IronLinuxFrontEnd"

      # Exports the app
      - name: Exporting app 💥
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: yarn workspace @iron-linux/frontend run export
        env:
          NEXT_PUBLIC_BASE_PATH: /IronLinuxFrontEnd

      # Creates a .nojekyll file to disable github jekyll
      - name: Creating ".nojekyll" file
        run: sudo touch ./packages/frontend/out/.nojekyll

      # Test the app
      - name: Testing the app 🧪
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: yarn workspace @iron-linux/frontend run test

      # Deploys the app
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/frontend/out # The folder the action should deploy.
